# Change 'comments' to true for Disqus comments


# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-'

menu: 
  - name: Featured Projects
    submenu:
      - name: MicroBam
        link: /projects/microbam
      - name: OurLegacy
        link: /projects/ourlegacy
   - name: About
    link: /about
   - name: tags
    link: /tags
   - name:Projects
    link: /
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/AifenLv
     
    
